name: My First Workflow sdfsdfg
on: [push] # The trigger

jobs:
  build:
    runs-on: ubuntu-latest # The virtual environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clones your repo into the runner

      - name: Run a script
        run: echo "The workflow is running successfully!"
